language: C
sudo: required
services:
- docker
stages:
- name: after_success
  if: branch = master
script:
- make -j2 && make test-binary
deploy:
  provider: script
  script: make release
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: GkFN2xcKiSMYHIZfBvOT1DBR6pcTXNUeuFlZ+XlcIeAyVD09nd8D306qLFJTArnNeMK55+R/iP0aFxIlGiTOUH0ubrUPJqVAc57nKH1RJZUHIil9tUIhYzvGuhD2efU2JBu207XWKAhMbOlgTlWN6dbp6NJwMb06qQTAbkn5f3w8jT8EkNaxhv5ZEOeKAyT/Rb1B4I2j4Nynh6PLa20vEGMa5iSZqy4UvQBEQBb3UwMt5uWhyl1g+rURP1VLd9nQuB4vabs96VPdhviuC/4v1AxhGrflQEmo2iCyxhjqHcfvVVaYHXUUXsGb1xVXWVZIf7pnGF1dDlY9wHrbvIbiFqPc43QZXCuyzqqahuC7fklX38gFOduAPfe/JmfTOpL1iNolL9Ejt/ZD13pm22QPhpVH2Cmdsh5Fc6t/i67PwPoeKRL51HODxmDbiqUsJUabjlhB4syugnbVJUv+TLpP99f5hMQ7s7gnqjckH/8yi4DXeexqLDwcaggDl7ctrHLnjrdRA8JlAfHkuDL2+XnhVSkOhajJNMTf7Fnl1iFQiahibGl2J6ILuFrcCJyQkDlKipUPn4WRjFsb0e4sQ/EbvaD7KEPm6PK7mgu0bbBbX+YxvFp/RNG/uZWgvLlpg4vm6j7Ags3HVfImOhx0xis4cr0CWaZzimv/xxkbrFhQWAI=
